---
label: Default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: title
  config:
    required: true
- type: tag_list
  name: tags
  label: tags
- type: text
  label: layout
  name: layout
  description: fancypost
  hidden: true
  config:
    required: true
- type: datetime
  name: date
  label: date
  config:
    date_format: YYYY-MM-DD
    required: true
- type: text
  name: background_url
  label: background url
